title: Mahyar Osanlouy # your name (or website title) here
logo: "/images/IMG_3817.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Fellow
  <br><br>
#  Second description
#  <br><br>
  <a href="https://www.linkedin.com/in/mahyar-osanlouy/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-177911637-1 # your Google Analytics tracking ID here
